import '../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex items-center justify-center mx-auto min-h-screen min-w-screen bg-gray-100 dark:bg-gray-900 antialiased'>
        {children}
      </body>
    </html>
  );
}
